#pragma once

enum curse_type
{
    CURSE_MELEE,
    CURSE_FIRST_CURSE = CURSE_MELEE,
    CURSE_RANGED,
#if TAG_MAJOR_VERSION == 34
    CURSE_ELEMENTS,
    CURSE_SORCERY,
    CURSE_COMPANIONS,
    CURSE_BEGUILING,
    CURSE_SELF,
    CURSE_FORTITUDE,
    CURSE_CUNNING,
#endif
    CURSE_DEVICES,
    CURSE_FIRE_MAGIC,
    CURSE_ICE_MAGIC,
    CURSE_AIR_MAGIC,
    CURSE_EARTH_MAGIC,
    CURSE_CONJURATIONS,
    CURSE_ALCHEMY,
    CURSE_SUMMONINGS,
    CURSE_NECROMANCY,
    CURSE_FORGECRAFT,
    CURSE_HEXES,
    CURSE_TRANSLOCATIONS,
    CURSE_SPELLCASTING,
    CURSE_ARMOUR,
    CURSE_SHIELDS,
    CURSE_DODGING,
    CURSE_STEALTH,
    CURSE_FIGHTING,
    NUM_CURSES,
};
