/**
 * Status defaults for durations.
 *
 * "" for an entry means N/A, either because it is not shown in the
 * relevant place, or because it is shown in a more complicated way.
 * A "" for name_text indicates that the name is the same as the
 * short text.
 *
 * Examples:
 *
 * DUR_FORESTED has "" for the short_text entry, and therefore has no
 * entry on the "@:" line.
 *
 * DUR_QAZLAL_AC has "" for the light_text entry, and therefore has no
 * status light (instead showing the AC bonus by coloring the player's
 * AC blue).
 */
struct duration_def
{
    duration_type dur;
    bool expire;         ///< Whether to do automatic expiration colouring.
    int    light_colour; ///< Base colour for status light.
    const char *light_text; ///< Text for the status light.
    const char *short_text; ///< Text for @ line on the % screen and morgues.
                            ///< Usually an adjective.
    const char *name_text;  ///< Text used in wizmode &^D. If empty, use the
                            ///< short_text.
    const char *long_text;  ///< Text for the @ message.

    bool dispellable;       ///< Whether !cancellation (and the like) end the duration.

    /// Return the name of the duration (name_text or short_text). */
    const char *name() const
    {
        return name_text[0] ? name_text : short_text;
    }
};

static const duration_def duration_data[] =
{
    { DUR_AGILITY,
      false, LIGHTBLUE, "Agi",
      "agile", "agility",
      "You are agile.", true },
    { DUR_ANTIMAGIC,
      true, RED, "-Mag",
      "antimagic", "",
      "You have trouble accessing your magic.", true /*!!!*/ },
    { DUR_BERSERK,
      true, BLUE, "Berserk",
      "berserking", "berserker",
      "You are possessed by a berserker rage.", false },
    { DUR_BREATH_WEAPON,
      false, YELLOW, "Breath",
      "short of breath", "breath weapon",
      "You are short of breath.", false },
    { DUR_BRILLIANCE,
      false, LIGHTBLUE, "Brill",
      "brilliant", "brilliance",
      "You are brilliant.", true },
    { DUR_CONF,
      false, RED, "Conf",
      "confused", "conf",
      "You are confused.", true },
    { DUR_CONFUSING_TOUCH,
      true, BLUE, "Touch",
      "confusing touch", "",
      "" , true },
    { DUR_CONTROL_TELEPORT,
      true, MAGENTA, "cTele",
      "controlling teleports", "control teleport",
      "You can control teleportations.", true },
    { DUR_CORONA,
      false, YELLOW, "Corona",
      "", "corona",
      "", true },
    { DUR_DEATH_CHANNEL,
      true, MAGENTA, "DChan",
      "death channel", "",
      "You are channeling the dead.", true },
    { DUR_DIVINE_STAMINA,
      true, WHITE, "Vit",
      "vitalised", "divine stamina",
      "You are divinely vitalised.", false },
    { DUR_DIVINE_VIGOUR,
      false, 0, "",
      "divinely vigorous", "divine vigour",
      "You are imbued with divine vigour.", false },
    { DUR_EXHAUSTED,
      false, YELLOW, "Exh",
      "exhausted", "",
      "You are exhausted.", false },
    { DUR_FIRE_SHIELD,
      true, BLUE, "RoF",
      "immune to fire clouds", "fire shield",
      "", true },
    { DUR_ICY_ARMOUR,
      true, 0, "",
      "icy armour", "",
      "You are protected by a layer of icy armour.", true },
    { DUR_LIQUID_FLAMES,
      false, RED, "Fire",
      "liquid flames", "",
      "You are covered in liquid flames.", false },
    { DUR_LOWERED_MR,
      false, RED, "-MR",
      "vulnerable", "lowered mr",
      "", false },
    { DUR_MAGIC_SHIELD,
      false, 0, "",
      "shielded", "magic shield",
      "", true },
    { DUR_MIGHT,
      false, LIGHTBLUE, "Might",
      "mighty", "might",
      "You are mighty.", true },
    { DUR_PARALYSIS,
      false, RED, "Para",
      "paralysed", "paralysis",
      "You are paralysed.", true },
    { DUR_PETRIFIED,
      false, RED, "Stone",
      "petrified", "",
      "You are petrified.", true },
    { DUR_PETRIFYING,
      true, LIGHTRED, "Petr",
      "petrifying", "",
      "You are turning to stone.", true /*but special-cased*/},
    { DUR_RESISTANCE,
      true, BLUE, "Resist",
      "resistant", "resistance",
      "You resist elements.", true },
    { DUR_SLIMIFY,
      true, GREEN, "Slime",
      "slimy", "slimify",
      "", false },
    { DUR_SLEEP,
      false, 0, "",
      "sleeping", "sleep",
      "You are sleeping.", false },
    { DUR_STONESKIN,
      false, 0, "",
      "stone skin", "stoneskin",
      "Your skin is tough as stone.", true },
    { DUR_SWIFTNESS,
      true, BLUE, "Swift",
      "swift", "swiftness",
      "You can move swiftly.", true },
    { DUR_TELEPATHY,
      false, LIGHTBLUE, "Emp",
      "empathic", "telepathy",
      "", false },
    { DUR_TELEPORT,
      false, LIGHTBLUE, "Tele",
      "about to teleport", "teleport",
      "You are about to teleport.", true /*but special-cased*/ },
    { DUR_DEATHS_DOOR,
      true, LIGHTGREY, "DDoor",
      "death's door", "deaths door",
      "", false },
    { DUR_PHASE_SHIFT,
      true, 0, "",
      "phasing", "phase shift",
      "You are out of phase with the material plane.", true },
    { DUR_QUAD_DAMAGE,
      true, BLUE, "Quad",
      "quad damage", "",
      "", false },
    { DUR_SILENCE,
      true, MAGENTA, "Sil",
      "silence", "",
      "You radiate silence.", true },
    { DUR_STEALTH,
      false, BLUE, "Stealth",
      "especially stealthy", "stealth",
      "", true },
    { DUR_AFRAID,
      true, RED, "Fear",
      "afraid", "",
      "You are terrified.", true },
    { DUR_MIRROR_DAMAGE,
      false, WHITE, "Mirror",
      "injury mirror", "mirror damage",
      "You mirror injuries.", false },
    { DUR_SCRYING,
      false, WHITE, "Scry",
      "scrying", "",
      "Your astral vision lets you see through walls.", false },
    { DUR_TORNADO,
      true, LIGHTGREY, "Tornado",
      "tornado", "",
      "You are in the eye of a mighty hurricane.", false },
    { DUR_LIQUEFYING,
      false, LIGHTBLUE, "Liquid",
      "liquefying", "",
      "The ground has become liquefied beneath your feet.", true },
    { DUR_HEROISM,
      false, LIGHTBLUE, "Hero",
      "heroism", "",
      "You possess the skills of a mighty hero.", false },
    { DUR_FINESSE,
      false, LIGHTBLUE, "Finesse",
      "finesse", "",
      "Your blows are lightning fast.", false },
    { DUR_LIFESAVING,
      true, LIGHTGREY, "Prot",
      "protection", "lifesaving",
      "You are calling for your life to be saved.", false },
    { DUR_DARKNESS,
      true, BLUE, "Dark",
      "darkness", "",
      "You emit darkness.", true },
    { DUR_SHROUD_OF_GOLUBRIA,
      true, BLUE, "Shroud",
      "shrouded", "",
      "You are protected by a distorting shroud.", true },
    { DUR_TORNADO_COOLDOWN,
      false, YELLOW, "Tornado",
      "", "tornado cooldown",
      "", false },
    { DUR_DISJUNCTION,
      true, BLUE, "Disjoin",
      "disjoining", "disjunction",
      "You are disjoining your surroundings.", true },
    { DUR_SENTINEL_MARK,
      true, LIGHTRED, "Mark",
      "marked", "sentinel's mark",
      "A sentinel's mark is revealing your location to enemies.", true },
    { DUR_INFUSION,
      true, BLUE, "Infus",
      "infused", "",
      "Your attacks are magically infused.", true },
    { DUR_SONG_OF_SLAYING,
      true, BLUE, "Slay",
      "singing", "song of slaying",
      "Your melee attacks are strengthened by your song.", true },
    { DUR_FLAYED,
      true, RED, "Flay",
      "flayed", "",
      "You are covered in terrible wounds.", false },
    { DUR_WEAK,
      false, RED, "Weak",
      "weakened", "weak",
      "Your attacks are enfeebled.", true },
    { DUR_DIMENSION_ANCHOR,
      false, RED, "-Tele",
      "cannot translocate", "dimension anchor",
      "You are firmly anchored to this plane.", true },
    { DUR_TOXIC_RADIANCE,
      false, MAGENTA, "Toxic",
      "radiating poison", "toxic radiance",
      "You are radiating toxic energy.", true },
    { DUR_RECITE,
      false, WHITE, "Recite",
      "reciting", "",
      "You are reciting Zin's Axioms of Law.", false },
    { DUR_GRASPING_ROOTS,
      false, BROWN, "Roots",
      "grasped by roots", "grasping roots",
      "Your movement is impeded by grasping roots.", false },
    { DUR_FIRE_VULN,
      false, RED, "-rF",
      "fire vulnerable", "fire vulnerability",
      "You are more vulnerable to fire.", true },
    { DUR_BARBS,
      false, RED, "Barbs",
      "manticore barbs", "",
      "Manticore spikes are embedded in your body.", false },
    { DUR_POISON_VULN,
      false, RED, "-rP",
      "poison vulnerable", "poison vulnerability",
      "You are more vulnerable to poison.", true },
    { DUR_FROZEN,
      false, RED, "Frozen",
      "frozen", "",
      "You are partly encased in ice.", false },
    { DUR_SAP_MAGIC,
      false, RED, "Sap",
      "sap magic", "",
      "Casting spells hinders your spell success.", true },
    { DUR_PORTAL_PROJECTILE,
      false, LIGHTBLUE, "PProj",
      "portal projectile", "",
      "You are teleporting projectiles to their destination.", true },
    { DUR_FORESTED,
      false, GREEN, "Forest",
      "", "forested",
      "", false },
    { DUR_DRAGON_CALL,
      false, WHITE, "Dragoncall",
      "dragon's call", "dragon call",
      "You are beckoning forth a horde of dragons.", false },
    { DUR_DRAGON_CALL_COOLDOWN,
      false, YELLOW, "Dragoncall",
      "", "dragon call cooldown",
      "", false },
    { DUR_ABJURATION_AURA,
      false, BLUE, "Abj",
      "aura of abjuration", "",
      "You are abjuring all hostile summons around you.", true },
    { DUR_NO_POTIONS,
      false, RED, "-Potion",
      "no potions", "",
      "You cannot drink potions.", false },
    { DUR_QAZLAL_FIRE_RES,
      false, LIGHTBLUE, "rF+",
      "protected from fire", "qazlal fire resistance",
      "Qazlal is protecting you from fire.", false },
    { DUR_QAZLAL_COLD_RES,
      false, LIGHTBLUE, "rC+",
      "protected from cold", "qazlal cold resistance",
      "Qazlal is protecting you from cold.", false },
    { DUR_QAZLAL_ELEC_RES,
      false, LIGHTBLUE, "rElec+",
      "protected from electricity", "qazlal elec resistance",
      "Qazlal is protecting you from electricity.", false },
    { DUR_QAZLAL_AC,
      false, LIGHTBLUE, "",
      "protected from physical damage", "qazlal ac",
      "Qazlal is protecting you from physical damage.", false },
    { DUR_CORROSION,
      false, RED, "Corr",
      "corroded equipment", "corrosion",
      "Your equipment is corroded.", false },
    { DUR_FORTITUDE,
      false, LIGHTBLUE, "Fort",
      "immense fortitude", "",
      "You have immense fortitude and shrug off injury.", true },
    { DUR_HORROR,
      false, RED, "Horr",
      "horrified", "",
      "You are horrified, weakening your attacks and spells.", false },
    { DUR_NO_SCROLLS,
      false, RED, "-Scroll",
      "no scrolls", "",
      "You cannot read scrolls.", false },
    { DUR_CONDENSATION_SHIELD,
      false, 0, "",
      "icy shield", "",
      "You are shielded by a disc of ice.", true },
    { DUR_DIVINE_SHIELD,
      false, 0, "",
      "divine shield", "",
      "You are shielded by the power of the Shining One.", false },
    { DUR_NEGATIVE_VULN,
      false, RED, "-rN",
      "negative energy vulnerable", "negative energy vulnerability",
      "You are more vulnerable to negative energy.", true },
    { DUR_CLEAVE,
      false, LIGHTBLUE, "Cleave",
      "cleaving", "cleave",
      "You are cleaving through your foes.", true },

    // The following are visible in wizmode only, or are handled
    // specially in the status lights and/or the % or @ screens.

    { DUR_INVIS, false, 0, "", "", "invis", "", true },
    { DUR_SLOW, false, 0, "", "", "slow", "", true },
    { DUR_MESMERISED, false, 0, "", "", "mesmerised", "", true },
    { DUR_MESMERISE_IMMUNE, false, 0, "", "", "mesmerisation immunity", "" },
    { DUR_HASTE, false, 0, "", "", "haste", "", true },
    { DUR_FLIGHT, false, 0, "", "", "flight", "", true /*but special-cased*/ },
    { DUR_POISONING, false, 0, "", "", "poisoning", "", false },
    { DUR_SURE_BLADE, false, 0, "", "", "sure blade", "", true },
    { DUR_PIETY_POOL, false, 0, "", "", "piety pool", "", false },
    { DUR_REGENERATION, false, 0, "", "", "regeneration", "", true },
    { DUR_TRANSFORMATION, false, 0, "", "", "transformation", "", true /*but special-cased*/ },
    { DUR_WEAPON_BRAND, false, 0, "", "", "weapon brand", "", true },
    { DUR_DEMONIC_GUARDIAN, false, 0, "", "", "demonic guardian", "", false },
    { DUR_POWERED_BY_DEATH, false, 0, "", "", "pbd", "", false },
    { DUR_GOURMAND, false, 0, "", "", "gourmand", "", false },
    { DUR_REPEL_STAIRS_MOVE, false, 0, "", "", "repel stairs move", "", false },
    { DUR_REPEL_STAIRS_CLIMB, false, 0, "", "", "repel stairs climb", "", false },
    { DUR_COLOUR_SMOKE_TRAIL, false, 0, "", "", "coloured smoke trail", "", false },
    { DUR_TIME_STEP, false, 0, "", "", "time step", "", false },
    { DUR_ICEMAIL_DEPLETED, false, 0, "", "", "icemail depleted", "", false },
    { DUR_PARALYSIS_IMMUNITY, false, 0, "", "", "paralysis immunity", "", false },
    { DUR_VEHUMET_GIFT, false, 0, "", "", "vehumet gift", "", false },
    { DUR_SICKENING, false, 0, "", "", "sickening", "", true },
    { DUR_WATER_HOLD, false, 0, "", "", "drowning", "", false },
    { DUR_WATER_HOLD_IMMUNITY, false, 0, "", "", "drowning immunity", "", false },
    { DUR_SLEEP_IMMUNITY, false, 0, "", "", "sleep immunity", "", false },
    { DUR_ELIXIR_HEALTH, false, 0, "", "", "elixir health", "", true },
    { DUR_ELIXIR_MAGIC, false, 0, "", "", "elixir magic", "", true },
    { DUR_TROGS_HAND, false, 0, "", "", "trogs hand", "", false },
    { DUR_MAGIC_SAPPED, false, 0, "", "", "magic sapped", "", true },

#if TAG_MAJOR_VERSION == 34
    // And removed ones
    { DUR_REPEL_MISSILES, false, 0, "", "", "old repel missiles", "", false },
    { DUR_DEFLECT_MISSILES, false, 0, "", "", "old deflect missiles", "", false },
    { DUR_JELLY_PRAYER, false, 0, "", "", "old jelly prayer", "", false },
    { DUR_CONTROLLED_FLIGHT, false, 0, "", "", "old controlled flight", "", false },
    { DUR_SEE_INVISIBLE, false, 0, "", "", "old see invisible", "", false },
    { DUR_INSULATION, false, 0, "", "", "old insulation", "", false },
    { DUR_BARGAIN, false, 0, "", "", "old bargain", "", false },
    { DUR_SLAYING, false, 0, "", "", "old slaying", "", false },
    { DUR_MISLED, false, 0, "", "", "old misled", "", false },
    { DUR_NAUSEA, false, 0, "", "", "old nausea", "", false },
    { DUR_TEMP_MUTATIONS, false, 0, "", "", "old temporary mutations", "", false },
    { DUR_BATTLESPHERE, false, 0, "", "", "old battlesphere", "", false },
    { DUR_RETCHING, false, 0, "", "", "old retching", "", false },
    { DUR_SPIRIT_HOWL, false, 0, "", "", "old spirit howl", "", false },
    { DUR_SONG_OF_SHIELDING, false, 0, "", "", "old song of shielding", "", false },
    { DUR_ANTENNAE_EXTEND, false, 0, "", "", "old antennae extend", "", false },
    { DUR_AMBROSIA, false, 0, "", "", "old ambrosia", "", false },
    { DUR_BUILDING_RAGE, false, 0, "", "", "old building rage", "", false },
#endif
};
