#pragma once

enum ieoh_jian_attack_type
{
    IEOH_JIAN_ATTACK_NONE,
    IEOH_JIAN_ATTACK_LUNGE,
    IEOH_JIAN_ATTACK_WHIRLWIND,
    IEOH_JIAN_ATTACK_WALL_JUMP,
    IEOH_JIAN_ATTACK_TRIGGERED_AUX,
};
