/**
 * @file localise.cc
 * @brief String localisation (translation)
 **/

#include "AppHdr.h"
#include "clua.h"
#include "database.h"
#include "english.h"
#include "localise.h"
#include "localise-util.h"
#include "pattern.h"
#include "options.h"
#include "stringutil.h"

#include <algorithm>
#include <map>
#include <string>
#include <vector>

using namespace std;

//#define debuglog(...) {fprintf(stderr, "DEBUG: %s: ", __FUNCTION__); fprintf (stderr, __VA_ARGS__); fprintf(stderr, "\n");}

#ifndef debuglog
#define debuglog(...) {}
#endif

static string _translate(const string &s, bool fallback_en = false);
static string _ctx_translate(const string &context, const string &s, bool fallback_en = false);

static string _localise_string(const string& s, bool fallback_en = true);
static string _localise_parameterised_string(const string& s, bool full_sentence_only = false);

// translations pregenerated by regex rules
static map<string, string> _pregenerated;

// regex rules for matching finished strings to parameterised strings
static vector<pair<text_pattern, string>> _patterns;

static bool _initialised = false;
static string _context;

static string _get_pregenerated_translation(const string& s)
{
    auto iter = _pregenerated.find(s);
    if (iter == _pregenerated.end())
        return "";
    else
        return iter->second;
}

static vector<string> get_pregenerated_keys_by_regex(const string& re)
{
    vector<string> keys;
    text_pattern pattern(re);
    for (const auto& entry: _pregenerated)
    {
        if (pattern.matches(entry.first))
            keys.push_back(entry.first);
    }
    return keys;
}

static vector<string> get_all_keys_by_regex(const string& re)
{
    vector<string> keys = getTranslationKeysByRegex(re);
    vector<string> keys2 = get_pregenerated_keys_by_regex(re);
    keys.insert(keys.end(), keys2.begin(), keys2.end());
    return keys;
}

// do pre-generation for translated strings
static void _do_pregeneration()
{
    for (int i = 0; i <= 100; i++)
    {
        string rulesKey = "PREGENERATE:" + to_string(i);
        string rulesStr = getTranslatedString(rulesKey);
        if (rulesStr.empty())
            continue;

        vector<string> rules = split_string("\n", rulesStr, true, false);

        // get selection regex
        string key_select_regex, value_select_regex;
        for (string rule: rules)
        {
            rule = trimmed_string(rule);
            bool is_key_select = starts_with(rule, "SELECT_BY_KEY");
            bool is_value_select = starts_with(rule, "SELECT_BY_VALUE");

            if (is_key_select || is_value_select)
            {
                size_t pos = rule.find(':');
                if (pos == string::npos)
                    break;

                string rule_regex = trimmed_string(rule.substr(pos + 1));
                if (starts_with(rule_regex, "/"))
                    rule_regex = rule_regex.substr(1);
                if (ends_with(rule_regex, "/"))
                    rule_regex = rule_regex.substr(0, rule_regex.length()-1);

                if (is_key_select)
                    key_select_regex = rule_regex;
                else
                    value_select_regex = rule_regex;
                break;
            }
        }

        if (key_select_regex.empty() && value_select_regex.empty())
            continue;

        vector<string> keys;
        if (!key_select_regex.empty())
            keys = get_all_keys_by_regex(key_select_regex);
        //else if (!value_select_regex.empty())
        //    keys = getTranslatedBodiesByRegex(value_select_regex);

        for (const string& orig_key: keys)
        {
            string key = orig_key;
            string orig_value = _translate(key);
            string value = orig_value;
            for (string rule: rules)
            {
                if (starts_with(rule, "KEY:"))
                {
                    rule = rule.substr(4);
                    key = apply_regex_rule(rule, key);
                }
                else
                    value = apply_regex_rule(rule, value);
            }

            // don't overwrite an existing translation
            if (key == orig_key || _translate(key) != "")
                continue;

            _pregenerated[key] = value;
        }
    }
    debuglog("%ld pregenerated translation strings", (long)_pregenerated.size());
}

void init_localisation()
{
    if (_initialised || Options.language == lang_t::EN)
        return;
    _initialised = true;

    static const text_pattern single_char_patt("^.$");
    if (!single_char_patt.matches("の"))
        fprintf(stderr, "WARNING: Regex is not UTF-8 aware\n");

    _do_pregeneration();

    // get all translation keys which contain parameters
    vector<string> keys = get_all_keys_by_regex("@[^@]+@");
    debuglog("%ld parameterised translation strings", (long)keys.size());

    // sort with longest strings first because we want to match the longest string possible
    std::sort(keys.begin(), keys.end(), [](const string& a, const string& b) {
        return length_excl_params(a) > length_excl_params(b);
    });

    // convert paramaterised string to regex pattern
    static const text_pattern player_name_patt("@player_name[^@]*@", true);
    static const text_pattern num_arg_patt("@num[^@]*@", true);
    static const text_pattern int_arg_patt("@integer[^@]*@", true);
    static const text_pattern float_arg_patt("@float[^@]*@", true);
    static const text_pattern punct_arg_patt("@punct[^@]*@", true);
    static const text_pattern str_arg_patt("@[^@]+@");
    static const text_pattern a_an_patt("^an? ");
    for (const string& key: keys)
    {
        if (starts_with(lowercase_string(key), "@sentence@"))
        {
            // don't store patterns for variable punctuation because we do special handling
            continue;
        }

        string pattern = key;
        // escape characters that mean something to regex
        pattern = escape_regex_specials(pattern);
        pattern = replace_all(pattern, "@two_letter_code@", "([A-Z][A-Za-z])");
        pattern = player_name_patt.replace(pattern, "([A-Za-z0-9._ -]+)");
        pattern = num_arg_patt.replace(pattern, "([0-9]+)");
        pattern = int_arg_patt.replace(pattern, "([\\+\\-]?[0-9]+)");
        // float is problematic because decimal point may already be changed by user's locale
        //pattern = float_arg_patt.replace(pattern, "([\\+|\\-]?[0-9]*[\\.,][0-9]+)");
        pattern = punct_arg_patt.replace(pattern, "([.!?]+)");
        pattern = str_arg_patt.replace(pattern, "([^.!?]*)");
        // adjectives can change "a" to "an" or vice versa
        pattern = a_an_patt.replace(pattern, "an? ");
        pattern = "^" + pattern + "$";

        if (replace_all(pattern, "(.*)", "") == "")
        {
            fprintf(stderr, "WARNING: Ignoring \"%s\" because it would match any text\n",
                    key.c_str());
            continue;
        }

        if (contains(pattern, "(.*)(.*)"))
        {
            fprintf(stderr, "WARNING: \"%s\" contains adjacent string parameters.\n"
                    "There is no way to tell where one value ends and the next starts.\n",
                    key.c_str());
        }

        _patterns.emplace_back(make_pair(text_pattern(pattern), key));
    }
    debuglog("Localisation initialised");
}

void shutdown_localisation()
{
    _pregenerated.clear();
    _patterns.clear();
    _initialised = false;
}

// low-level translate function
static string _translate(const string &s, bool fallback_en)
{
    string result = getTranslatedString(s);

    if (result.empty())
        result = _get_pregenerated_translation(s);

    // the presence of an adjective can change "a" to "an" or vice versa
    if (result.empty() && (starts_with(s, "a ") || starts_with(s, "an ")))
    {
        string alternative;
        if (starts_with(s, "a "))
            alternative = "an" + s.substr(1);
        else
            alternative = "a" + s.substr(2);

        result = getTranslatedString(alternative);

        if (result.empty())
            result = _get_pregenerated_translation(alternative);
    }

    if (result.empty() && fallback_en)
        result = s;

    return result;
}

// low-level translate function with context
static string _ctx_translate(const string &context, const string &s, bool fallback_en)
{
    if (context.empty())
        return _translate(s);

    string result;

    // first try with context
    result = _translate(add_context(context, s));
    if (!result.empty())
        return result;

    // get translation for default context
    result = _translate(s);

    if (!result.empty())
    {
        // look for rules to convert to required context
        string rules = getTranslatedString(string("GENERATE:") + context);
        if (!rules.empty())
        {
            // convert default string to context using rules
            result = apply_regex_rules(rules, result);
        }
    }

    if (result.empty() && fallback_en)
        result = s;

    return result;
}

// if string starts with a context, remove it and set current context to that
static string _shift_context(const string& str)
{
    string result = str;
    while (starts_with(result, "{"))
    {
        size_t pos = result.find('}');
        if (pos == string::npos)
            break;

        _context = result.substr(1, pos - 1);
        result = result.substr(pos + 1);
    }

    return result;
}

static int _get_matching_pattern_index(const string& s, bool full_sentence_only = false)
{
    if (s.empty())
        return -1;

    string punct;
    if (full_sentence_only)
    {
        punct = get_end_punctuation(s);
        if (punct.empty())
            return -1;
    }

    for (size_t i = 0; i < _patterns.size(); i++)
    {
        // do some quick tests first to reduce the amount of regex
        // (POSIX regex is slow)
        const string& param_str = _patterns[i].second;
        if (param_str.empty())
            continue;
        if (param_str[0] != '@' && param_str[0] != s[0])
            continue;
        size_t last = param_str.length() - 1;
        if (param_str[last] != '@' && param_str[last] != s[s.length() - 1])
            continue;
        if (s.length() < length_excl_params(param_str))
            continue;

        if (_patterns[i].first.matches(s))
        {
            if (full_sentence_only)
            {
                string format = _patterns[i].second;
                string punct2 = get_end_punctuation(format);
                if (punct2 == punct)
                    return (int)i;

                // variable punctuation placeholder
                static const text_pattern punct_patt("@punct[^@]*@$");
                if (punct_patt.matches(format))
                    return (int)i;
            }
            else
                return (int)i;
        }
    }

    return -1;
}

static string _localise_adjectives(const string& s)
{
    string result;

    size_t start = 0;
    size_t end = s.find(' ');

    while (true)
    {
        string adj;
        if (end == string::npos)
            adj = s.substr(start);
        else
            adj = s.substr(start, end - start + 1);

        if (is_determiner(adj))
            return "";

        if (!is_adverb(adj) || end == string::npos)
        {
            string xlated = _ctx_translate(_context, adj);
            if (xlated.empty() && ends_with(adj, " "))
            {
                // try without space
                string adj2 = adj.substr(0, adj.length() - 1);
                xlated = _ctx_translate(_context, adj2);
                if (!xlated.empty())
                    xlated += " ";
            }
            result += xlated.empty() ? adj : xlated;

            if (end == string::npos)
                break;

            start = end + 1;
        }

        end = s.find(' ', end + 1);
    }

    return result;
}


static string _localise_param(map<string, string>& params, const string& key)
{
    string new_key = lowercase_first(key);
    string old_key;
    string old_val;

    if (params.count(new_key))
    {
        old_key = new_key;
        old_val = params[old_key];
    }
    else
    {
        // translation may add or remove determiners

        // try to find a related key that was in the original string
        string base_key = strip_determiner(new_key);
        if (params.count(base_key))
            old_key = base_key;
        else if (params.count("the_" + base_key))
            old_key = "the_" + base_key;
        else if (params.count("a_" + base_key))
            old_key = "a_" + base_key;
        else if (params.count("your_" + base_key))
            old_key = "your_" + base_key;

        if (old_key.empty())
            return "@" + key + "@";

        // get the original base string
        old_val = params[old_key];
        bool old_val_had_determiner = has_determiner(old_val);
        old_val = strip_determiner(old_val);

        // add the relevant determiner to the original base string
        if (old_val_had_determiner || !starts_with_uppercase(old_val))
        {
            if (starts_with(new_key, "the_"))
                old_val = "the " + old_val;
            else if (starts_with(new_key, "a_"))
                old_val = article_a(old_val);
            else if (starts_with(new_key, "your_"))
                old_val = "your " + old_val;
        }
    }

    if (old_key.empty() || old_val.empty())
        return "";

    string new_val;

    if (new_key == "player_name")
    {
        // don't mess with it
        new_val = old_val;
    }
    else
    {
        new_val = _localise_string(old_val, false);

        // old val might be capitalised due to being at start of sentence
        if (new_val.empty() && starts_with_uppercase(old_val))
            new_val = _localise_string(lowercase_first(old_val), false);

        if (new_val.empty() && contains(old_val, ' '))
            new_val = _localise_adjectives(old_val);

        if (new_val.empty())
            new_val = old_val;
    }

    _shift_context(new_val);

    return isaupper(key[0]) ? uppercase_first(new_val) : new_val;
}

// In deference to Spanish, which likes to put punctuation at both ends,
// variable punctuation is handled by passing the sentence as a parameter
// to the punctuation string, rather than vice versa.
static string _handle_variable_punctuation(const string& rest, const string& punct)
{
    if (punct.empty())
        return "";

    string format = _translate("@Sentence@" + punct, true);
    if (format.empty())
        return "";

    string result = replace_first(format, "@sentence@", rest);
    result = replace_first(result, "@Sentence@", uppercase_first(rest));
    return result;
}

// Get the correct plural form for languages that have different forms for different numbers.
// For example, Russian has one plural form for 2-4, and a different one for 5-10.
// Returns the context specificer for the correct plural form
static string _get_correct_plural_form(const string& s)
{
    string plural_rules = getTranslatedString("PLURAL_RULES");
    trim_string(plural_rules);
    if (plural_rules.empty())
        return "";

    // extract the number from the string to be translated
    static const text_pattern number_pattern("[0-9]+");
    pattern_match match = number_pattern.match_location(s);
    if (!match)
        return "";
    string num_str = match.matched_text();

    vector<string> rules = split_string("\n", plural_rules, true, false);
    for (string rule: rules)
    {
        trim_string(rule);
        if (rule.empty())
            continue;

        vector<string> tokens = split_string(":", rule, true, false);
        if (tokens.size() != 2)
            continue;

        // evaluate the condition
        string expression = tokens[1];
        string lua_code = make_stringf("n=%s\nreturn %s", num_str.c_str(), expression.c_str());

        if (clua.execstring(lua_code.c_str(), "plural_lua", 1) != 0)
        {
            // error
            continue;
        }

        bool res;
        clua.fnreturns(">b", &res);
        if (res)
            return tokens[0];
    }

    return "";
}


// localise parameterised string
static string _localise_parameterised_string(const string& s, bool full_sentence_only)
{
    // try to find matching pattern
    int match_idx = _get_matching_pattern_index(s, full_sentence_only);
    if (match_idx < 0)
        return "";

    const pair<text_pattern, string>& match = _patterns[match_idx];
    debuglog("Param string: %s", match.second.c_str());

    vector<string> param_keys = extract_params(match.second);
    vector<string> param_vals = match.first.capture(s);

    if (param_keys.size() == 0)
    {
        debuglog("ERROR: No params in parameterised string... weird.");
        return "";

    }
    else if (param_keys.size() != param_vals.size())
    {
        debuglog("ERROR: %ld keys, %ld vals\n", (long)param_keys.size(), (long)param_vals.size());
        return "";
    }

    map<string, string> params;
    for (size_t i = 0; i < param_keys.size(); i++)
    {
        // store all params with lowercase keys
        string key = lowercase_first(param_keys[i]);
        string value = maybe_lowercase_first(param_vals[i]);
        params[key] = value;
    }

    string format = match.second;

    string plural_form = _get_correct_plural_form(s);
    if (!plural_form.empty())
        format = _ctx_translate(plural_form, match.second);
    else
        format = _ctx_translate(_context, match.second);

    if (format.empty())
    {
        debuglog("No translation for: \"%s\"", match.second.c_str());
        return "";
    }
    debuglog("Param string translation: \"%s\"", format.c_str());

    string result;
    vector<string> tokens = tokenise_parameterised_string(format);

    for (const string& token: tokens)
    {
        size_t last_idx = token.length() - 1;
        if (token.length() >= 2 && token[0] == '{' && token[last_idx] == '}')
        {
            // context specifier
            _context = token.substr(1, token.length() - 2);
        }
        else if (token.length() >= 3 && token[0] == '@' && token[last_idx] == '@')
        {
            // parameter
            string key = token.substr(1, token.length() - 2);
            if (starts_with(key, "punct"))
            {
                result = _handle_variable_punctuation(result, params[key]);
            }
            else
            {
                string saved_context = _context;
                string val = _localise_param(params, key);
                if (!saved_context.empty())
                    _context = saved_context;
                result += val;
            }
        }
        else
        {
            // plain string
            result += token;
        }
    }

    return result;
}

static string _localise_annotation(const string& s)
{
    if (s.empty())
        return s;

    string trimmed = trimmed_string(s);
    if (trimmed.length() != s.length())
    {
        string result = _localise_annotation(trimmed);
        return replace_all(s, trimmed, result);
    }

    size_t last = s.length() - 1;
    if (contains("([{", s[0]) && contains(")]}", s[last]))
        return s[0] + _localise_annotation(s.substr(1, s.length() - 2)) + s[last];

    if (contains(s, ','))
    {
        string result;
        vector<string> tokens = split_string(",", s, false, true);
        for (size_t i = 0; i < tokens.size(); i++)
        {
            if (i > 0)
                result += ",";
            result += _localise_annotation(tokens[i]);
        }

        return result;
    }

    string result;
    vector<string> tokens = split_string(" ", s, false, true);
    for (size_t i = 0; i < tokens.size(); i++)
    {
        if (i > 0)
            result += " ";
        result += _localise_string(tokens[i]);
    }

    return result;
}

static string _localise_string(const string& s, bool fallback_en)
{
    if (s.empty())
        return s;

    // check if all whitespace
    string trimmed = trimmed_string(s);
    if (trimmed.empty())
        return s;

    if (is_integer_string(trimmed))
        return s;

    // try simple translation first
    string result = _ctx_translate(_context, s);
    if (!result.empty())
    {
        result = _shift_context(result);
        return result;
    }

    if (trimmed.length() != s.length())
    {
        result = _localise_string(trimmed, fallback_en);
        if (!result.empty())
            return replace_first(s, trimmed, result);
    }

    string prefix, rest;
    separate_menu_letter_prefix(s, prefix, rest);
    if (!prefix.empty())
    {
        result = _localise_string(rest, fallback_en);
        if (!result.empty() || rest.empty())
            return prefix + result;
    }

    string annotation;
    separate_prefix_annotation(s, annotation, rest);
    if (!annotation.empty())
    {
        result = _localise_string(rest, fallback_en);
        if (!result.empty() || rest.empty())
            return _localise_annotation(annotation) + result;
    }

    separate_postfix_annotation(s, annotation, rest);
    if (!annotation.empty())
    {
        result = _localise_string(rest, fallback_en);
        if (!result.empty() || rest.empty())
            return result + _localise_annotation(annotation);
    }

    string punct = get_end_punctuation(s);
    if (!punct.empty())
    {
        // this is a sentence
        result = _localise_parameterised_string(s, true);
        if (!result.empty())
        {
            result = _shift_context(result);
            return result;
        }
    }

    // test for list
    auto tokens = tokenise_comma_separated_list(s);
    if (tokens.size() > 1)
    {
        for (string token: tokens)
        {
            string saved_context = _context;
            token = maybe_lowercase_first(token);
            result += _localise_string(token);
            if (!saved_context.empty())
                _context = saved_context;
        }
        return result;
    }

    // test for named ally (e.g. "Boghold the orc")
    // or shape-shifted unique (e.g. "Sigmund the bat")
    text_pattern named_mon("^[A-Z][a-z]+ the ");
    pattern_match match = named_mon.match_location(s);
    if (match)
    {
        int start = match.start_pos();
        int end = match.end_pos() - 5;
        if (start >= 0 && end <= (int)s.length() && end > start + 1)
        {
            string name = s.substr(start, end - start);
            rest = s.substr(end);
            string xlated_name = strip_context(_translate(name));
            if (xlated_name.empty())
                xlated_name = name;
            result = _localise_string(rest, fallback_en);
            if (!result.empty())
                return xlated_name + result;
        }
    }


    result = _localise_parameterised_string(s, false);
    if (!result.empty())
    {
        result = _shift_context(result);
        return result;
    }

    debuglog("No translation found for \"%s\"", s.c_str());
    return fallback_en ? s : "";
}

bool localisation_active()
{
    return Options.language != lang_t::EN && _initialised;
}

string localise(const string &s)
{
    if (!localisation_active())
        return s;

    if (s.empty())
        return s;

    debuglog("IN:  \"%s\"", s.c_str());
    string result;

    // localise lines individually
    auto lines = split_string("\n", s, false, true);
    for (size_t i = 0; i < lines.size(); i++)
    {
        if (i > 0)
            result += "\n";
        if (lines[i].empty() || trimmed_string(lines[i]).empty())
            result += lines[i];
        else
        {
            _context = "";
            string line = _localise_string(lines[i]);
            result += line;
        }
    }

    debuglog("OUT: \"%s\"", result.c_str());
    return result;
}
