#pragma once

enum lookup_help_type
{
    LOOKUP_HELP_MONSTER,
    FIRST_LOOKUP_HELP_TYPE = LOOKUP_HELP_MONSTER,
    LOOKUP_HELP_SPELL,
    LOOKUP_HELP_SKILL,
    LOOKUP_HELP_ABILITY,
    LOOKUP_HELP_CARD,
    LOOKUP_HELP_ITEM,
    LOOKUP_HELP_FEATURE,
    LOOKUP_HELP_GOD,
    LOOKUP_HELP_BRANCH,
    LOOKUP_HELP_CLOUD,
    LOOKUP_HELP_PASSIVE,
    LOOKUP_HELP_STATUS,
    LOOKUP_HELP_MUTATION,
    LOOKUP_HELP_BANE,
    LOOKUP_HELP_WEAPON_EGO,
    LOOKUP_HELP_ARMOUR_EGO,
    LOOKUP_HELP_MISSILE_EGO,
    NUM_LOOKUP_HELP_TYPES
};
