#include "mon-book.h"

/* *********************************************************************

    This file determines which spells are contained in monster spellbooks.
    It is used by /util/gen-mst.pl to generate spellbook enums, which are
    listed in mon-mst.h.

    Template Format:

    {    mon_spellbook_type,
        {
            { spell type, frequency, flags },
            { spell type, frequency, flags },
            { spell type, frequency, flags },
            { spell type, frequency, flags },
            { spell type, frequency, flags },
            { spell type, frequency, flags }
        }
    }

********************************************************************* */

static const mon_spellbook mspell_list[] =
{
    {  MST_ORC_WIZARD_I,
      {
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORC_WIZARD_II,
      {
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORC_WIZARD_III,
      {
       { SPELL_THROW_FROST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CANTRIP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_UNBORN,
      {
       { SPELL_AGONY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INJURY_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HAUNT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INJURY_MIRROR, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BK_TROG,
      {
       { SPELL_BROTHERS_IN_ARMS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TROGS_HAND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BERSERKER_RAGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BK_YREDELEMNUL,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INJURY_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRAIN_LIFE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRAIN_LIFE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GUARDIAN_SERPENT,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_ALLIES_ENCIRCLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_LICH_I,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_LICH_II,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BANISHMENT, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_LICH_III,
      {
       { SPELL_CORROSIVE_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_LICH_IV,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELLION,
      {
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_VAMPIRE,
      {
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_VAMPIRE_KNIGHT,
      {
       { SPELL_BLINK_CLOSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_VAMPIRE_MAGE,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_EFREET,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BRAIN_WORM,
      {
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GIANT_ORANGE_BRAIN,
      {
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CAUSE_FEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MASS_CONFUSION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_RAKSHASA,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PHANTOM_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PHANTOM_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GREAT_ORB_OF_EYES,
      {
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISINTEGRATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRAIN_MAGIC, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_KRAKEN,
      {
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INK_CLOUD, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORC_SORCERER,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_STEAM_DRAGON,
      {
       { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELL_KNIGHT_I,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELL_KNIGHT_II,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NECROMANCER_I,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AGONY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SIMULACRUM, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NECROMANCER_II,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AGONY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIZARD_I,
      {
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIZARD_II,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIZARD_III,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIZARD_IV,
      {
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BANISHMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIZARD_V,
      {
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORC_PRIEST,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CANTRIP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HEAL_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORC_HIGH_PRIEST,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HEAL_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MOTTLED_DRAGON,
      {
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FIEND,
      {
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELL_SENTINEL,
      {
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ICE_FIEND,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SHADOW_FIEND,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TORMENTOR,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_STORM_DRAGON,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WHITE_IMP,
      {
       { SPELL_THROW_FROST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_YNOXINUL,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UFETUBUS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UFETUBUS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NEQOXEC,
      {
       { SPELL_MALMUTATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELLWING,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SMOKE_DEMON,
      {
       { SPELL_STICKY_FLAME_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CACODEMON,
      {
       { SPELL_ENERGY_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALMUTATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DIG, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GREEN_DEATH,
      {
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BALRUG,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BLIZZARD_DEMON,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FREEZING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TITAN,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GOLDEN_DRAGON,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_SUMMONER,
      {
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_VERMIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_VERMIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_VERMIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_CONJURER,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_PRIEST,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALIGN_OFFERING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TWISTED_RESURRECTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_HIGH_PRIEST,
      {
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALIGN_OFFERING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TWISTED_RESURRECTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_DEMONOLOGIST,
      {
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BANISHMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_ANNIHILATOR,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_SORCERER,
      {
       { SPELL_CORROSIVE_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BANISHMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_ELF_DEATH_MAGE,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CALL_LOST_SOUL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TWISTED_RESURRECTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_KOBOLD_DEMONOLOGIST,
      {
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CANTRIP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CANTRIP, 0, MON_SPELL_NO_FLAGS }, // this should be cute -- bw
      },
    },

    {  MST_NAGA,
      {
       { SPELL_SPIT_POISON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SPIT_POISON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NAGA_MAGE,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CURSE_SKULL,
      {
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SHINING_EYE,
      {
       { SPELL_MALMUTATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALMUTATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FROST_GIANT,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANGEL,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DAEVA,
      {
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SHADOW_DRAGON,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SPHINX,
      {
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MUMMY,
      {
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ELECTRIC_GOLEM,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORB_OF_FIRE,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALMUTATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SHADOW_IMP,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELL_HOG,
      {
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_SPLASH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SWAMP_DRAGON,
      {
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SWAMP_DRAKE,
      {
       { SPELL_NOXIOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NOXIOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NOXIOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NOXIOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SERPENT_OF_HELL,
      {
       { SPELL_SERPENT_OF_HELL_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SERPENT_OF_HELL_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAGON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAGON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SERPENT_OF_HELL_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAGON, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BOGGART,
      {
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_EYE_OF_DEVASTATION,
      {
       { SPELL_ENERGY_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ENERGY_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ENERGY_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ENERGY_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_QUICKSILVER_DRAGON,
      {
       { SPELL_QUICKSILVER_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_QUICKSILVER_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_QUICKSILVER_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_QUICKSILVER_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IRON_DRAGON,
      {
       { SPELL_METAL_SPLINTERS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_METAL_SPLINTERS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_METAL_SPLINTERS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_METAL_SPLINTERS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NORRIS,
      {
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEATH_DRAKE,
      {
       { SPELL_MIASMA_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIASMA_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIASMA_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIASMA_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRAC_SCORCHER,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRAC_CALLER,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAKES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAKES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DRAKES, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRAC_SHIFTER,
      {
       { SPELL_DIMENSION_ANCHOR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_ALLIES_ENCIRCLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_AWAY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // Curse toe menu should be kept full, because otherwise the toe spends
    // too much time crawling around.
    {  MST_CURSE_TOE,
      {
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MUSHROOMS, 0, MON_SPELL_NO_FLAGS }, // fungal theme
       { SPELL_SUMMON_MUSHROOMS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MUSHROOMS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ICE_STATUE,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FREEZING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ICE_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ICE_BEAST, 0, MON_SPELL_NO_FLAGS }, // in Zotdef forced off
      }
    },

    // fake spell for monsters berserking when fleeing
    {  MST_BERSERK_ESCAPE,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BERSERKER_RAGE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MERFOLK_AQUAMANCER,
      {
        { SPELL_PRIMAL_WAVE, 0, MON_SPELL_NO_FLAGS },
        { SPELL_STEAM_BALL, 0, MON_SPELL_NO_FLAGS },
        { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
        { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
        { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
        { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ALLIGATOR,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SWIFTNESS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // ---------------------
    // uniques' "spellbooks"
    // ---------------------

    // Jessica is now a bit more evil-themed than before.
    {  MST_JESSICA,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS }, // Formerly Magic Dart.
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS }, // Formerly Magic Dart.
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_RUPERT,
      {
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BERSERKER_RAGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BERSERKER_RAGE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // statue, earth spells
    // Blink Other for foes out of the other spells' range
    { MST_ROXANNE,
      {
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_OTHER_CLOSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SONJA,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    { MST_MENKAURE,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    { MST_EUSTACHIO,
      {
       { SPELL_SUMMON_SMALL_MAMMAL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    { MST_ILSUIW,
      {
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CALL_TIDE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WATER_ELEMENTALS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WATER_ELEMENTALS, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_PRINCE_RIBBIT,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NESSOS,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_KIRKE,
      {
       { SPELL_PORKALATOR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MONSTROUS_MENAGERIE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PORKALATOR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DOWAN,
      {
       { SPELL_THROW_FROST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FANNAR,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_OZOCUBUS_REFRIGERATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ICE_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ICE_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_OZOCUBUS_REFRIGERATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GASTRONOK,
      {
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SWIFTNESS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_SMALL_MAMMAL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CANTRIP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MAURICE,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SWIFTNESS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // demon lords
    {  MST_GERYON,
      {
       { SPELL_SUMMON_HELL_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_HELL_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_HELL_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_HELL_BEAST, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DISPATER,
      {
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ASMODEUS,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIRE_SUMMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ERESHKIGAL,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SILENCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MAJOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANTAEUS,
      {
       { SPELL_FLASH_FREEZE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FLASH_FREEZE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MNOLEG,
      {
       { SPELL_SUMMON_EYEBALLS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_HORRIBLE_THINGS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_HORRIBLE_THINGS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_LOM_LOBON,
      {
       { SPELL_GLACIATE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONJURE_BALL_LIGHTNING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MAJOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TORNADO, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TORNADO, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CEREBOV,
      {
       { SPELL_FIRE_STORM, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_GREATER_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GLOORX_VLOQ,
      {
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIASMA_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_KHUFU,
      {
       { SPELL_SUMMON_EMPEROR_SCORPIONS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TOMB_OF_DOROKLOHE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NIKOLA,
      {
       { SPELL_SHOCK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CHAIN_LIGHTNING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CHAIN_LIGHTNING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DISSOLUTION,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_EYEBALLS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_EYEBALLS, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_AIZUL,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLEEP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_EXECUTIONER,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IGNACIO,
      {
       { SPELL_AGONY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HAROLD,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MARA,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FAKE_MARA_SUMMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ILLUSION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BORIS,
      {
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FREDERICK,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BK_OKAWARU,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIGHT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SPRIGGAN_DRUID,
      {
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AWAKEN_FOREST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRUIDS_CALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SPRIGGAN_AIR_MAGE,
      {
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONTROL_WINDS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    { MST_THE_ENCHANTRESS,
      {
       { SPELL_DIMENSION_ANCHOR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MASS_CONFUSION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STRIP_RESISTANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELLEPHANT,
      {
       { SPELL_FIRE_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIRE_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GRINDER,
      {
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IRON_ELEMENTAL,
      {
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_METAL_SPLINTERS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IRON_GIANT,
      {
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_ELEMENTALS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MENNAS,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SILENCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NERGALLE,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_SPECTRAL_ORCS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_SPECTRAL_ORCS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DEATHS_DOOR, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_JUMPING_SPIDER,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_CLOSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_AWAY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORB_SPIDER,
      {
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IOOD, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_PEARL_DRAGON,
      {
       { SPELL_HOLY_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_BREATH, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OPHAN,
      {
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_FLAMES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_FLAMES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BOG_BODY,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORPSE_ROT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_JORY,
      {
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MESMERISE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_CLOSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_EIDOLON,
      {
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CAUSE_FEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_BASILISK,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PETRIFY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CATOBLEPAS,
      {
       { SPELL_PETRIFYING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PETRIFYING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SHADOW_DEMON,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

#if TAG_MAJOR_VERSION == 34
    {  MST_SILVER_STAR,
      {
       { SPELL_HOLY_LIGHT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HOLY_LIGHT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SILVER_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SILVER_BLAST, 0, MON_SPELL_NO_FLAGS },
      }
    },
#endif

    {  MST_GNOLL_SHAMAN,
      {
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HEAL_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HEAL_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ARACHNE,
      {
       { SPELL_ENSNARE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISON_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ENSNARE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ENSNARE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_HELLBINDER,
      {
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_AWAY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CLOUD_MAGE,
      {
       { SPELL_MEPHITIC_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FREEZING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_RANGE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SOUL_EATER,
      {
       { SPELL_DRAIN_LIFE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WRETCHED_STAR,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENTACLED_STARSPAWN,
      {
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CREATE_TENTACLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FRANCES,
      {
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NATASHA,
      {
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CALL_IMP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MEPHITIC_CLOUD, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_THRASHING_HORROR,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIGHT, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_JORGRUN,
      {
       { SPELL_LRD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PETRIFY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHATTER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DIG, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_TROLL_EARTH_MAGE,
      {
       { SPELL_LRD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DIG, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEEP_TROLL_SHAMAN,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIGHT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_VAULT_SENTINEL,
      {
       { SPELL_SENTINEL_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SENTINEL_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SENTINEL_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IRONBRAND_CONVOKER,
      {
       { SPELL_MIGHT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MIGHT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WORD_OF_RECALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WORD_OF_RECALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_IRONHEART_PRESERVER,
      {
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INJURY_BOND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TEST_SPAWNER,
      {
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PLANEREND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PLANEREND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PHANTOM_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SHADOW_CREATURES, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANCIENT_CHAMPION_I,
      {
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PAIN, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANCIENT_CHAMPION_II,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANCIENT_CHAMPION_III,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HAUNT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ANCIENT_CHAMPION_IV,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_REVENANT,
      {
       { SPELL_GHOSTLY_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_GHOSTLY_FLAMES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_AWAY, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRYAD,
      {
       { SPELL_AWAKEN_VINES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AWAKEN_VINES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AWAKEN_FOREST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AWAKEN_FOREST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FAUN_I,
      {
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FAUN_II,
      {
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_FAUN_III,
      {
       { SPELL_CORONA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SATYR,
      {
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CAUSE_FEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CAUSE_FEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLEEP, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_CONJURER_I,
      {
       { SPELL_FORCE_LANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_CONJURER_II,
      {
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_CONJURER_III,
      {
       { SPELL_SHOCK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_CONJURER_IV,
      {
       { SPELL_MEPHITIC_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_REAVER_I,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FREEZING_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_REAVER_II,
      {
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_TENGU_REAVER_III,
      {
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORROSIVE_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_POISONOUS_CLOUD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SOJOBO,
      {
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WIND_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIR_ELEMENTALS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WIND_BLAST, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WIND_DRAKE,
      {
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AIRSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_THORN_HUNTER,
      {
       { SPELL_THORN_VOLLEY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THORN_VOLLEY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WALL_OF_BRAMBLES, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WATER_NYMPH,
      {
       { SPELL_WATERSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WATERSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WATERSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_WATERSTRIKE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRACONIAN_ZEALOT,
      {
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HELLFIRE_BURST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // deep elf ie
    {  MST_DEEP_ELF_MAGE_I,
      {
       { SPELL_FREEZE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FREEZE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_ICE_BEAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // deep elf ee
    {  MST_DEEP_ELF_MAGE_II,
      {
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // deep elf wz
    {  MST_DEEP_ELF_MAGE_III,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VENOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // deep elf --fe
    {  MST_DEEP_ELF_MAGE_IV,
      {
       { SPELL_FLAME_TONGUE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STICKY_FLAME_RANGE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    // deep elf cj
    {  MST_DEEP_ELF_MAGE_V,
      {
       { SPELL_MAGIC_DART, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FORCE_LANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BATTLESPHERE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },
    {  MST_ASTERION,
      {
       { SPELL_MAJOR_DESTRUCTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SPECTRAL_WEAPON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SPECTRAL_WEAPON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SPECTRAL_WEAPON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_RAIJU,
      {
       { SPELL_BLINKBOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OGRE_MAGE_I,
      {
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PARALYSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OGRE_MAGE_II,
      {
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CONFUSE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SLOW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_SELF, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OGRE_MAGE_III,
      {
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEHUDIBS_CRYSTAL_SPEAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_FIRE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OGRE_MAGE_IV,
      {
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BANISHMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MINOR_HEALING, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OGRE_MAGE_V,
      {
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_FLAME, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_TELEPORT_OTHER, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NAGA_SNIPER,
      {
       { SPELL_PORTAL_PROJECTILE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PORTAL_PROJECTILE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_NAGA_RITUALIST,
      {
       { SPELL_FORCE_LANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_OLGREBS_TOXIC_RADIANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_OLGREBS_TOXIC_RADIANCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VIRULENCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VIRULENCE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SALAMANDER_MYSTIC,
      {
       { SPELL_ISKENDERUNS_MYSTIC_BLAST, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE_OTHER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IGNITE_POISON_SINGLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_WORLDBINDER,
      {
       { SPELL_FORCEFUL_INVITATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FORCEFUL_INVITATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FORCEFUL_INVITATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_FORCEFUL_INVITATION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEMONSPAWN_BLOOD_SAINT,
      {
       { SPELL_LEGENDARY_DESTRUCTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_EPHEMERAL_INFUSION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LEGENDARY_DESTRUCTION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_EPHEMERAL_INFUSION, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEMONSPAWN_CORRUPTER,
      {
       { SPELL_PLANEREND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORRUPT_BODY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PLANEREND, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CORRUPT_BODY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEMONSPAWN_CHAOS_CHAMPION,
      {
       { SPELL_RANDOM_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CHAOTIC_MIRROR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEMONSPAWN_BLACK_SUN,
      {
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MALIGN_OFFERING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLACK_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLACK_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DEMONSPAWN_WARMONGER,
      {
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS }, // heh
       { SPELL_SAP_MAGIC, 0, MON_SPELL_NO_FLAGS },
       { SPELL_GRAND_AVATAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_GRAND_AVATAR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRACONIAN_KNIGHT_I,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_INVISIBILITY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SIMULACRUM, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRACONIAN_KNIGHT_II,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_LIGHTNING_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_AGONY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_DRACONIAN_KNIGHT_III,
      {
       { SPELL_BOLT_OF_COLD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_THROW_ICICLE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_HASTE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_OZOCUBUS_ARMOUR, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_VASHNIA,
      {
       { SPELL_PORTAL_PROJECTILE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_ALLIES_AWAY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_AWAY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PORTAL_PROJECTILE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_ALLIES_AWAY, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLINK_OTHER, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_CRYSTAL_GUARDIAN,
      {
       { SPELL_CRYSTAL_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CRYSTAL_BOLT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_CRYSTAL_BOLT, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GARGOYLE,
      {
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_STONE_ARROW, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MOLTEN_GARGOYLE,
      {
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BOLT_OF_MAGMA, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_OCTOPODE_CRUSHER,
      {
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_IRON_SHOT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MELEE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_JOSEPHINE,
      {
       { SPELL_GHOSTLY_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_GHOSTLY_FIREBALL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_VAMPIRIC_DRAINING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_ANIMATE_DEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DISPEL_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_SILVER_STATUE,
      {
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_MINOR_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ORANGE_CRYSTAL_STATUE,
      {
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRAIN_MAGIC, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MASS_CONFUSION, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BRAIN_FEED, 0, MON_SPELL_NO_FLAGS },
       { SPELL_DRAIN_MAGIC, 0, MON_SPELL_NO_FLAGS },
       { SPELL_MASS_CONFUSION, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_MURRAY,
      {
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLACK_MARK, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_BLACK_MARK, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_ELEMENTAL_WELLSPRING,
      {
       { SPELL_PRIMAL_WAVE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PRIMAL_WAVE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PRIMAL_WAVE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_PRIMAL_WAVE, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GREATER_MUMMY_I,
      {
       { SPELL_SUMMON_MANA_VIPER, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_UNDEAD, 0, MON_SPELL_NO_FLAGS },
      }
    },

    {  MST_GREATER_MUMMY_II,
      {
       { SPELL_SUMMON_DEMON, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SMITING, 0, MON_SPELL_NO_FLAGS },
       { SPELL_NO_SPELL, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SYMBOL_OF_TORMENT, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_EMPEROR_SCORPIONS, 0, MON_SPELL_NO_FLAGS },
       { SPELL_SUMMON_EMPEROR_SCORPIONS, 0, MON_SPELL_NO_FLAGS },
      }
    },

};
