#pragma once

enum terrain_change_type
{
    TERRAIN_CHANGE_GENERIC,
    TERRAIN_CHANGE_FLOOD,
    TERRAIN_CHANGE_TOMB,
    TERRAIN_CHANGE_IMPRISON,
    TERRAIN_CHANGE_DOOR_SEAL,
    TERRAIN_CHANGE_FORESTED,
    TERRAIN_CHANGE_WALL_CREATE,
    TERRAIN_CHANGE_BOG,
    TERRAIN_CHANGE_COLD,
    NUM_TERRAIN_CHANGE_TYPES
};
