// for unhardcode in *.cc file
// it was not complete.
// was worked target :
// ability.cc -> ability_def Ability_List array

// single line translate ( not format string )
//     ex) TR(x) some_single_line_translate_function(x)
//     or TR_FORMAT(x) some_other_language_s_format_string(x)

#ifndef TRANSLATE_H
#define TRANSLATE_H
#define TR(x) x

// ABIL_NAME was used by key
// and using in array
// should not translate by function

// DEFINE NAME method
// upper case, space to underbar, ' quote remove
// and add scope prefix like ABIL_NAME
#define ABIL_NAME_NO_ABILITY                   TR("No ability")
#define ABIL_NAME_SPIT_POISON                  TR("Spit Poison")
#define ABIL_NAME_BLINK                        TR("Blink")
#define ABIL_NAME_BREATHE_FIRE                 TR("Breathe Fire")
#define ABIL_NAME_BREATHE_FROST                TR("Breathe Frost")
#define ABIL_NAME_BREATHE_POISON_GAS           TR("Breathe Poison Gas")
#define ABIL_NAME_BREATHE_NOXIOUS_FUMES        TR("Breathe Noxious Fumes")
#define ABIL_NAME_BREATHE_LIGHTNING            TR("Breathe Lightning")
#define ABIL_NAME_BREATHE_DISPELLING_ENERGY    TR("Breathe Dispelling Energy")
#define ABIL_NAME_BREATHE_STICKY_FLAME         TR("Breathe Sticky Flame")
#define ABIL_NAME_BREATHE_STEAM                TR("Breathe Steam")
#define ABIL_NAME_BAT_FORM                     TR("Bat Form")
#define ABIL_NAME_SPIT_ACID                    TR("Spit Acid")
#define ABIL_NAME_FLY                          TR("Fly")
#define ABIL_NAME_STOP_FLYING                  TR("Stop Flying")
#define ABIL_NAME_HELLFIRE                     TR("Hellfire")
#define ABIL_NAME_RELEASE_DELAYED_FIREBALL     TR("Release Delayed Fireball")
#define ABIL_NAME_STOP_SINGING                 TR("Stop Singing")
#define ABIL_NAME_SELF-RESTORATION             TR("Self-Restoration")
#define ABIL_NAME_DIG                          TR("Dig")
#define ABIL_NAME_SHAFT_SELF                   TR("Shaft Self")
#define ABIL_NAME_EVOKE_TELEPORTATION          TR("Evoke Teleportation")
#define ABIL_NAME_EVOKE_BLINK                  TR("Evoke Blink")
#define ABIL_NAME_DEVICE_RECHARGING            TR("Device Recharging")
#define ABIL_NAME_EVOKE_BERSERK_RAGE           TR("Evoke Berserk Rage")
#define ABIL_NAME_EVOKE_INVISIBILITY           TR("Evoke Invisibility")
#define ABIL_NAME_TURN_VISIBLE                 TR("Turn Visible")
#define ABIL_NAME_EVOKE_FLIGHT                 TR("Evoke Flight")
#define ABIL_NAME_EVOKE_FOG                    TR("Evoke Fog")
#define ABIL_NAME_END_TRANSFORMATION           TR("End Transformation")
#define ABIL_NAME_RECITE                       TR("Recite")
#define ABIL_NAME_VITALISATION                 TR("Vitalisation")
#define ABIL_NAME_IMPRISON                     TR("Imprison")
#define ABIL_NAME_SANCTUARY                    TR("Sanctuary")
#define ABIL_NAME_CURE_ALL_MUTATIONS           TR("Cure All Mutations")
#define ABIL_NAME_DONATE_GOLD                  TR("Donate Gold")
#define ABIL_NAME_DIVINE_SHIELD                TR("Divine Shield")
#define ABIL_NAME_CLEANSING_FLAME              TR("Cleansing Flame")
#define ABIL_NAME_SUMMON_DIVINE_WARRIOR        TR("Summon Divine Warrior")
#define ABIL_NAME_BRAND_WEAPON_WITH_HOLY_WRATH TR("Brand Weapon With Holy Wrath")
#define ABIL_NAME_RECEIVE_CORPSES              TR("Receive Corpses")
#define ABIL_NAME_TORMENT                      TR("Torment")
#define ABIL_NAME_RECEIVE_NECRONOMICON         TR("Receive Necronomicon")
#define ABIL_NAME_BRAND_WEAPON_WITH_PAIN       TR("Brand Weapon With Pain")
#define ABIL_NAME_INJURY_MIRROR                TR("Injury Mirror")
#define ABIL_NAME_ANIMATE_REMAINS              TR("Animate Remains")
#define ABIL_NAME_RECALL_UNDEAD_SLAVES         TR("Recall Undead Slaves")
#define ABIL_NAME_ANIMATE_DEAD                 TR("Animate Dead")
#define ABIL_NAME_DRAIN_LIFE                   TR("Drain Life")
#define ABIL_NAME_ENSLAVE_SOUL                 TR("Enslave Soul")
#define ABIL_NAME_ANIMATE_REMAINS_OR_DEAD      TR("Animate Remains or Dead")
#define ABIL_NAME_HEROISM                      TR("Heroism")
#define ABIL_NAME_FINESSE                      TR("Finesse")
#define ABIL_NAME_MINOR_DESTRUCTION            TR("Minor Destruction")
#define ABIL_NAME_LESSER_SERVANT_OF_MAKHLEB    TR("Lesser Servant of Makhleb")
#define ABIL_NAME_MAJOR_DESTRUCTION            TR("Major Destruction")
#define ABIL_NAME_GREATER_SERVANT_OF_MAKHLEB   TR("Greater Servant of Makhleb")
#define ABIL_NAME_CHANNEL_ENERGY               TR("Channel Energy")
#define ABIL_NAME_FORGET_SPELL                 TR("Forget Spell")
#define ABIL_NAME_BURN_SPELLBOOKS              TR("Burn Spellbooks")
#define ABIL_NAME_BERSERK                      TR("Berserk")
#define ABIL_NAME_TROGS_HAND                   TR("Trog's Hand")
#define ABIL_NAME_BROTHERS_IN_ARMS             TR("Brothers in Arms")
#define ABIL_NAME_DIVINE_PROTECTION            TR("Divine Protection")
#define ABIL_NAME_LESSER_HEALING               TR("Lesser Healing")
#define ABIL_NAME_HEAL_OTHER                   TR("Heal Other")
#define ABIL_NAME_PURIFICATION                 TR("Purification")
#define ABIL_NAME_GREATER_HEALING              TR("Greater Healing")
#define ABIL_NAME_DIVINE_VIGOUR                TR("Divine Vigour")
#define ABIL_NAME_DEPART_THE_ABYSS             TR("Depart the Abyss")
#define ABIL_NAME_BEND_SPACE                   TR("Bend Space")
#define ABIL_NAME_BANISH                       TR("Banish")
#define ABIL_NAME_CORRUPT                      TR("Corrupt")
#define ABIL_NAME_ENTER_THE_ABYSS              TR("Enter the Abyss")
#define ABIL_NAME_BRAND_WEAPON_WITH_DISTORTION TR("Brand Weapon With Distortion")
#define ABIL_NAME_TRIPLE_DRAW                  TR("Triple Draw")
#define ABIL_NAME_DEAL_FOUR                    TR("Deal Four")
#define ABIL_NAME_STACK_FIVE                   TR("Stack Five")
#define ABIL_NAME_SMITING                      TR("Smiting")
#define ABIL_NAME_RECALL_ORCISH_FOLLOWERS      TR("Recall Orcish Followers")
#define ABIL_NAME_GIVE_ITEM_TO_NAMED_FOLLOWER  TR("Give Item to Named Follower")
#define ABIL_NAME_REQUEST_JELLY                TR("Request Jelly")
#define ABIL_NAME_JELLY_PARALYSE               TR("Jelly Paralyse")
#define ABIL_NAME_SLIMIFY                      TR("Slimify")
#define ABIL_NAME_CURE_BAD_MUTATION            TR("Cure Bad Mutation")
#define ABIL_NAME_EVOLUTION                    TR("Evolution")
#define ABIL_NAME_SUNLIGHT                     TR("Sunlight")
#define ABIL_NAME_GROWTH                       TR("Growth")
#define ABIL_NAME_REPRODUCTION                 TR("Reproduction")
#define ABIL_NAME_RAIN                         TR("Rain")
#define ABIL_NAME_BEND_TIME                    TR("Bend Time")
#define ABIL_NAME_TEMPORAL_DISTORTION          TR("Temporal Distortion")
#define ABIL_NAME_SLOUCH                       TR("Slouch")
#define ABIL_NAME_STEP_FROM_TIME               TR("Step From Time")
#define ABIL_NAME_SCRYING                      TR("Scrying")
#define ABIL_NAME_TRANSFER_KNOWLEDGE           TR("Transfer Knowledge")
#define ABIL_NAME_END_TRANSFER_KNOWLEDGE       TR("End Transfer Knowledge")
#define ABIL_NAME_SHADOW_STEP                  TR("Shadow Step")
#define ABIL_NAME_SHADOW_FORM                  TR("Shadow Form")
#define ABIL_NAME_DRAW_OUT_POWER               TR("Draw Out Power")
#define ABIL_NAME_POWER_LEAP                   TR("Power Leap")
#define ABIL_NAME_APOCALYPSE                   TR("Apocalypse")
#define ABIL_NAME_SACRIFICE_PURITY             TR("Sacrifice Purity")
#define ABIL_NAME_SACRIFICE_WORDS              TR("Sacrifice Words")
#define ABIL_NAME_SACRIFICE_DRINK              TR("Sacrifice Drink")
#define ABIL_NAME_SACRIFICE_ESSENCE            TR("Sacrifice Essence")
#define ABIL_NAME_SACRIFICE_HEALTH             TR("Sacrifice Health")
#define ABIL_NAME_SACRIFICE_STEALTH            TR("Sacrifice Stealth")
#define ABIL_NAME_SACRIFICE_ARTIFICE           TR("Sacrifice Artifice")
#define ABIL_NAME_SACRIFICE_LOVE               TR("Sacrifice Love")
#define ABIL_NAME_SACRIFICE_COURAGE            TR("Sacrifice Courage")
#define ABIL_NAME_SACRIFICE_ARCANA             TR("Sacrifice Arcana")
#define ABIL_NAME_SACRIFICE_NIMBLENESS         TR("Sacrifice Nimbleness")
#define ABIL_NAME_SACRIFICE_DURABILITY         TR("Sacrifice Durability")
#define ABIL_NAME_SACRIFICE_A_HAND             TR("Sacrifice a Hand")
#define ABIL_NAME_SACRIFICE_EXPERIENCE         TR("Sacrifice Experience")
#define ABIL_NAME_SACRIFICE_SKILL              TR("Sacrifice Skill")
#define ABIL_NAME_SACRIFICE_AN_EYE             TR("Sacrifice an Eye")
#define ABIL_NAME_SACRIFICE_RESISTANCE         TR("Sacrifice Resistance")
#define ABIL_NAME_REJECT_SACRIFICES            TR("Reject Sacrifices")
#define ABIL_NAME_POTION_PETITION              TR("Potion Petition")
#define ABIL_NAME_CALL_MERCHANT                TR("Call Merchant")
#define ABIL_NAME_BRIBE_BRANCH                 TR("Bribe Branch")
#define ABIL_NAME_UPHEAVAL                     TR("Upheaval")
#define ABIL_NAME_ELEMENTAL_FORCE              TR("Elemental Force")
#define ABIL_NAME_DISASTER_AREA                TR("Disaster Area")
#define ABIL_NAME_STOP_RECALL                  TR("Stop Recall")
#define ABIL_NAME_RENOUNCE_RELIGION            TR("Renounce Religion")
#define ABIL_NAME_CONVERT_TO_BEOGH             TR("Convert to Beogh")

#endif
