#!/usr/bin/env python3

"""
Works with both Python 2 & 3. If that changes, update how the Makefile calls
this.
"""

from subprocess import Popen, PIPE

import os
import sys

if len(sys.argv) < 2:
    sys.stderr.write('CXX not specified\n')
    sys.exit(1)
CXX = sys.argv[1]

command = sys.argv[1:]
command.append('-c');
command.append('conftest.cc');

out = open('conftest.cc', 'w')
out.write("""
#include <unistd.h>
int main()
{
    fdatasync(1);
    return 0;
}
""")
out.close()

process = Popen(command, stdout=PIPE, stderr=PIPE)
(output, err) = process.communicate()
exit_code = process.wait()
FDATASYNC = "#define CRAWL_HAVE_FDATASYNC" if exit_code == 0 else "#undef CRAWL_HAVE_FDATASYNC"

out = open('conftest.cc', 'w')
out.write("""
#include <cstring>
using namespace std;
int main()
{
    const char *src = "hello";
    char dst[10];
    strlcpy(dst, src, sizeof(dst));
    return 0;
}
""")
out.close()

process = Popen(command, stdout=PIPE, stderr=PIPE)
(output, err) = process.communicate()
exit_code = process.wait()
STRLCPY = "#define CRAWL_HAVE_STRLCPY" if exit_code == 0 else "#undef CRAWL_HAVE_STRLCPY"

out = open('conftest.cc', 'w')
out.write("""
#include <cstdlib>
using namespace std;
int main()
{
    char file[] = "XXXXXX";
    mkstemp(file);
    return 0;
}
""")
out.close()

process = Popen(command, stdout=PIPE, stderr=PIPE)
(output, err) = process.communicate()
exit_code = process.wait()
MKSTEMP = "#define CRAWL_HAVE_MKSTEMP" if exit_code == 0 else "#undef CRAWL_HAVE_MKSTEMP"

out = open('conftest.cc', 'w')
out.write("""
#include <unistd.h>
int main()
{
    usleep(0);
    return 0;
}
""")
out.close()

process = Popen(command, stdout=PIPE, stderr=PIPE)
(output, err) = process.communicate()
exit_code = process.wait()
USLEEP = "#define CRAWL_HAVE_USLEEP" if exit_code == 0 else "#undef CRAWL_HAVE_USLEEP"

try:
    os.remove('conftest.cc')
except OSError:
    pass

try:
    os.remove('conftest.o')
except OSError:
    pass

try:
    os.remove('conftest.obj')
except OSError:
    pass

out = open('config.h', 'w')
out.write("""
#pragma once

// Generated by util/configure.py

""")
out.write(FDATASYNC)
out.write('\n')
out.write(STRLCPY)
out.write('\n')
out.write(MKSTEMP)
out.write('\n')
out.write(USLEEP)
out.write('\n')
out.close()
