#!/bin/sh

# Includes may depend on a generated header, let's not unnecessarily require
# compilation just to gather strings.
#
# Use a future version tag, we remove descs immediately even though the item/
# monster is fully removed only after a save compat bump.
sed '/^ *# *include/d ; /^ *# *pragma *once/d' "$1"|cpp -x c++ -DTAG_MAJOR_VERSION=999 --std=c++11 -
