#!/usr/bin/perl -w

sub err($)
{
    print STDERR $_[0];
}

sub __________________________________________________________________________
{
    %entries = (); # per-db
    %source = (); # file:line
    %keys = (); # per-file
}

sub read_file($)
{
    %keys = ();
    $file = $_[0];
    $line = 0;
    open F, "<dat/$file.txt" or die "Can't read dat/$file.txt\n";
    ($key, $value) = ();
    local $_;
    
    sub add_key()
    {
        err "Duplicate entry: '$key' at $source{$key} and $file:$line\n"
            if $source{$key};
        $source{$key} = "$file:$line";
        $entries{$key} = $value;
        $keys{$key} = 1;

        undef $key;
        undef $value;
    }
    
    while (<F>)
    {
        next if /^#/;
        s/\s+$//;

        if (/^%%%%/)
        {
            add_key() if defined $key;
            next;
        }

        unless (defined $key)
        {
            next if /^$/;
            $key = $_;
            $line = $.; # report the start not end of a desc
        }
        else
        {
            next if /^$/ && !defined $value;
            $value .= $_;
        }
    }

    if (defined $key)
    {
        defined($value)
        ? add_key()
        : err("Incomplete entry '$key' at the end of '$file'\n");
    }

    close F;
}

__________________________________________________________________________();
read_file("descript/features");
read_file("descript/items");
read_file("descript/unident");
read_file("descript/unrand");
read_file("descript/spells");
read_file("descript/gods");
read_file("descript/branches");
read_file("descript/skills");
read_file("descript/ability");
read_file("descript/commands");

read_file("descript/cards");
for (`util/gather_cards`)
{
    chomp;
    err "$file: No description for card '$_'\n" unless $entries{"$_ card"};
    delete $keys{"$_ card"};
}
delete $keys{'a buggy card'};
delete $keys{'a very buggy card'};
err "$file: Unused description for card '$_'\n" for sort keys %keys;

read_file("descript/monsters");
$entries{$_} = 1 for ('the Serpent of Hell', 'player', 'player illusion',
                      'merged slime creature');
for (`util/gather_mons`)
{
    chomp;
    # using a desc from another file is ok, it's the same db
    err "$file: No description for monster '$_'\n" unless $entries{$_};
    delete $keys{$_}
}

delete $keys{'__(_suffix_examine'};
for (sort keys %keys)
{
    next if /^__cap-[A-Z]_suffix$/;
    next if /^the Serpent of Hell (?:gehenna|cocytus|dis|tartarus)$/;
    err "$file: Unused description for monster '$_'\n";
}


__________________________________________________________________________();
read_file("descript/$_") for qw(species backgrounds);
__________________________________________________________________________();
read_file("database/$_") for qw(randname rand_wpn rand_arm rand_all randbook monname);
__________________________________________________________________________();
read_file("database/$_") for qw(monspeak monspell monflee wpnnoise insult godspeak);
__________________________________________________________________________();
read_file("database/$_") for qw(shout insult);
__________________________________________________________________________();
read_file("descript/quotes");
__________________________________________________________________________();
read_file("database/help");
__________________________________________________________________________();
read_file("database/FAQ");
