#!/usr/bin/env perl

use warnings;

undef $/;
open IN, "util/cpp_version branch-data.h|" or die "Can't read branch-data.h\n";
$_ = <IN>;
close IN;

s|//.*$||gm;

print "$_\n" for
    /{\s*BRANCH_[A-Z_]+, \s*[A-Z_]+, \s*[0-9-]+, \s*[0-9-]+, \s*[0-9-]+, \s*[0-9-]+,
    \s*[^,\n]+,
    \s*[^,\n]+, \s*[^,\n]+,
    \s*"([^"\n"]+)",/sgx;
