#include <cstdio>
#include <string>
#include "levcomp.h"

map_def map;
level_range range;
level_range default_depth;

const char *autogenheader =
    "/*************************************************************\n"
    " * WARNING: This file is automatically generated! Do not edit.\n"
    " *************************************************************/\n";

const char *outfilename = NULL;
FILE *outhandle = NULL;
bool autowarned = false;
bool write_append = false;

extern int yyparse();

int main(int argc, char **argv) {
    for (int i = 1; i < argc; ++i) {
        if (argv[i][0] == '-') {
            if (argv[i][1] == 'a')
            {
                write_append = true;
            }
        }
        else
            outfilename = argv[i];
    }
    return yyparse();
}
