#!/bin/sh

cd "$(git rev-parse --show-toplevel)"
[ $(git diff-index --raw --name-only HEAD | grep "\.png$" | wc -l) != 0 ] \
    || (echo "No changed .png files -- please 'git add' them first." && exit)
git diff-index --raw --name-only -z HEAD | grep -zZ --color=never "\.png$" | xargs -0 optipng -o4 -i0 -fix
git diff-index --raw --name-only -z HEAD | grep -zZ --color=never "\.png$" | xargs -0 advpng -z4
