.Dd October 9, 2021
.Os
.Dt CRAWL 6
.Sh NAME
.Nm Crawl
.Nd a roguelike dungeon exploration game
.Sh SYNOPSIS
.Nm
.Op Fl vscores Ar n
.Op Fl tscores Ar n
.Op Fl test
.Op Fl sprint-map Ar map
.Op Fl sprint
.Op Fl species Ar species
.Op Fl seed Ar num
.Op Fl script Ar file
.Op Fl scores Ar n
.Op Fl scorefile Ar path
.Op Fl rcdir Ar path
.Op Fl rc Ar path
.Op Fl plain
.Op Fl name Ar name
.Op Fl morgue Ar path
.Op Fl macro Ar path
.Op Fl help
.Op Fl extra-opt-last Ar optname Ns = Ns Ar optval
.Op Fl extra-opt-first Ar optname Ns = Ns Ar optval
.Op Fl dir Ar path
.Op Fl builddb
.Op Fl background Ar background
.Op Fl arena Op Qq Ar monsters Cm v Ar monsters Op Cm arena: Ns Ar map
.Sh DESCRIPTION
.Nm
is a fun game in the grand tradition of similar games like Rogue,
Hack and Moria. The objective is to travel deep into a subterranean cave
complex and retrieve the Orb of Zot, guarded by many horrible and hideous
creatures.
.Pp
If you have never played
.Nm
(or a similar game) before, select the
tutorial from the starting menu. The tutorial explains the interface in
five easy lessons. Once you're familiar with the controls, you may want to
play a few games using hints mode.
.Pp
This is the Stone Soup version of Dungeon Crawl.
.Sh ENVIRONMENT
.Bl -tag -width "CRAWL_NAME" -compact
.It Ev CRAWL_NAME
The character name to use.
.It Ev CRAWL_DIR
The directory to store information in.
.It Ev CRAWL_RC
The configuration file to use.
.El
.Sh SUPPORT
Please visit https://crawl.develz.org for further information.
.Sh SEE ALSO
The in-game help menu, which can be accessed by pressing
.Ic \&? .
.Sh COPYRIGHT
Copyright 1997-2021 Linley Henzell, the dev team, and the contributors.
.Pp
Crawl is distributed under the terms of the GNU General Public License
version 2 or later.
