.TH CRAWL 6
.SH NAME
crawl \- play the roguelike game of crawl
.SH SYNOPSIS
.BR crawl
[options]
.PP
Use the "\-help" option to get a list of command line options and their descriptions.
.SH DESCRIPTION
Crawl is a fun game in the grand tradition of games like Rogue, Hack, and
Moria. Your objective is to travel deep into a subterranean cave complex and
retrieve the Orb of Zot, which is guarded by many horrible and hideous
creatures.
.PP
To access Crawl's help menu, press '?'. To get the list of all commands,
press '?' again.
.SH AUTHORS
Copyright 1997, 1998, 1999 Linley Henzell
