#!/usr/bin/perl

# This is utter and complete hackery.  But I'm tired
# of building the mac distribution by hand.

$script= $0;
$script =~ /(.*)\/MacOS\/(\w+)/;
$scriptdir = $1;
$resdir = $scriptdir . "/Resources/";
$executable = $resdir . "crawl";
if (-e "/Applications/Utilities/Terminal.app")
{
	system "/usr/bin/open -a /Applications/Utilities/Terminal.app '$executable'";
}
else
{
	# moved in catalina, and it's connected using a "firmlink" that isn't visible in
	# the file system.
	system "/usr/bin/open -a /System/Applications/Utilities/Terminal.app '$executable'";
}
