#!/bin/sh

set -e

echo "*******************************************"
echo "Building Mac console release build"
echo "*******************************************"
./mac/mac-release-console-build "$@"

echo "*******************************************"
echo "Building Mac tiles release build"
echo "*******************************************"
./mac/mac-release-tiles-build "$@"
